import type { Action, Belief, Claim, Observation, Outcome } from "@qmilab/lodestar-core"
import type { ChainProjection, FirewallTransition, ProjectedAction } from "./chain.js"

/**
 * Render an epistemic chain projection as a markdown trust report.
 *
 * The output is meant to be readable on its own: dropped into a GitHub
 * issue, a Slack message, or a PR comment, it should give the reader a
 * clear picture of "what the agent observed, what it came to believe,
 * which beliefs informed which actions, what happened, and whether
 * anything was revised."
 *
 * Sections are omitted when empty so that small sessions produce
 * compact reports.
 */
export interface RenderOptions {
  /** Title used at the top of the report. Defaults to "Lodestar trust report". */
  title?: string
  /**
   * Maximum number of raw events to list verbatim in the "Event log"
   * section. Set to 0 to suppress that section entirely.
   */
  raw_event_limit?: number
}

export function renderReport(projection: ChainProjection, options: RenderOptions = {}): string {
  const title = options.title ?? "Lodestar trust report"
  const lines: string[] = []

  lines.push(`# ${title}`)
  lines.push("")
  lines.push(...renderHeader(projection))
  lines.push("")

  const sections: Array<{ heading: string; body: string[] }> = [
    { heading: "## Observations", body: renderObservations(projection.observations) },
    { heading: "## Claims", body: renderClaims(projection.claims) },
    {
      heading: "## Evidence",
      body: renderEvidence(projection.evidence_sets, projection.claims),
    },
    { heading: "## Beliefs", body: renderBeliefs(projection.beliefs, projection.claims) },
    { heading: "## Decisions", body: renderDecisions(projection.decisions) },
    { heading: "## Actions", body: renderActions(projection.actions) },
    { heading: "## Firewall activity", body: renderTransitions(projection.transitions) },
    {
      heading: "## Cognitive ingestion",
      body: renderCognitiveSummaries(projection.cognitive_summaries),
    },
  ]

  for (const { heading, body } of sections) {
    if (body.length === 0) continue
    lines.push(heading)
    lines.push("")
    lines.push(...body)
    lines.push("")
  }

  if (options.raw_event_limit && options.raw_event_limit > 0) {
    lines.push("## Event log (raw)")
    lines.push("")
    const limited = projection.raw_events.slice(0, options.raw_event_limit)
    lines.push("| seq | clock | type | actor |")
    lines.push("|-----|-------|------|-------|")
    for (const e of limited) {
      lines.push(`| ${e.seq} | ${e.logical_clock} | \`${e.type}\` | \`${e.actor_id}\` |`)
    }
    if (projection.raw_events.length > limited.length) {
      lines.push("")
      lines.push(`_…${projection.raw_events.length - limited.length} more event(s) elided._`)
    }
    lines.push("")
  }

  lines.push(...renderFooter(projection))
  return lines.join("\n")
}

function renderHeader(p: ChainProjection): string[] {
  const lines: string[] = []
  lines.push(`**Session**: \`${p.session_id || "(unknown)"}\``)
  lines.push(`**Project**: \`${p.project_id || "(unknown)"}\``)
  if (p.actor_ids.size > 0) {
    const actors = Array.from(p.actor_ids).sort()
    lines.push(`**Actors**: ${actors.map((a) => `\`${a}\``).join(", ")}`)
  }
  if (p.first_event_at && p.last_event_at) {
    const span =
      p.first_event_at === p.last_event_at
        ? p.first_event_at
        : `${p.first_event_at} → ${p.last_event_at}`
    lines.push(`**Time**: ${span}`)
  }
  lines.push(`**Events**: ${p.event_count}`)
  return lines
}

function renderFooter(p: ChainProjection): string[] {
  const lines: string[] = []
  lines.push("---")
  lines.push("")
  lines.push(
    "_Generated by `@qmilab/lodestar-trace` from the append-only event log. Every claim, " +
      "belief, and action above is linked back to an event in the log; the report " +
      "is a projection, not a summary._",
  )
  if (p.beliefs.length === 0 && p.transitions.length === 0) {
    lines.push("")
    lines.push(
      "> **Note**: this session emitted no full `belief.adopted` payloads or firewall " +
        "audit events. The agent ran but the trust layer did not record its " +
        "epistemic state — investigate whether the guard was wired up.",
    )
  }
  return lines
}

function renderObservations(observations: Observation[]): string[] {
  if (observations.length === 0) return []
  const lines: string[] = []
  for (const obs of observations) {
    lines.push(
      `- \`${obs.source.tool}\` — schema \`${obs.schema}\`, trust \`${obs.trust}\`, ` +
        `sensitivity \`${obs.sensitivity}\` (\`${obs.id.slice(0, 8)}\`)`,
    )
  }
  return lines
}

function renderClaims(claims: Claim[]): string[] {
  if (claims.length === 0) return []
  const lines: string[] = []
  for (const claim of claims) {
    lines.push(
      `- _${claim.extraction_method}_ ${claim.statement}  ` +
        `\`(${claim.status}, sensitivity ${claim.sensitivity})\``,
    )
  }
  return lines
}

function renderEvidence(
  evidence_sets: ChainProjection["evidence_sets"],
  claims: Claim[],
): string[] {
  if (evidence_sets.length === 0) return []
  const claimById = new Map(claims.map((c) => [c.id, c]))
  const lines: string[] = []
  for (const set of evidence_sets) {
    const claim = claimById.get(set.claim_id)
    const heading = claim?.statement ?? `(claim ${set.claim_id.slice(0, 8)})`
    lines.push(`- **${heading}**`)
    for (const item of set.items) {
      const indep = item.independence_group ? ` · indep \`${item.independence_group}\`` : ""
      const notes = item.notes ? ` — ${item.notes}` : ""
      lines.push(
        `    - ${item.relation} · quality \`${item.quality}\` · freshness \`${item.freshness}\`${indep}${notes}`,
      )
    }
  }
  return lines
}

function renderBeliefs(beliefs: Belief[], claims: Claim[]): string[] {
  if (beliefs.length === 0) return []
  const claimById = new Map(claims.map((c) => [c.id, c]))
  const lines: string[] = []
  for (const b of beliefs) {
    const claim = claimById.get(b.claim_id)
    const statement = claim?.statement ?? `(claim ${b.claim_id.slice(0, 8)})`
    const axes =
      `truth=\`${b.truth_status}\` · retrieval=\`${b.retrieval_status}\` · ` +
      `security=\`${b.security_status}\` · freshness=\`${b.freshness_status}\``
    lines.push(`- **${statement}**`)
    lines.push(
      `    - confidence ${b.confidence.toFixed(2)} · ${axes} · ` +
        `authority \`${b.authority}\` · class \`${b.calibration_class}\``,
    )
  }
  return lines
}

function renderDecisions(decisions: ChainProjection["decisions"]): string[] {
  if (decisions.length === 0) return []
  const lines: string[] = []
  for (const d of decisions) {
    const heading = d.question ?? `(decision ${d.id?.slice(0, 8) ?? "?"})`
    const idTag = d.id ? ` \`(${d.id.slice(0, 8)})\`` : ""
    lines.push(`- **${heading}**${idTag}`)
    if (d.chosen_option !== undefined) {
      const summary = describeChosenOption(d.chosen_option)
      if (summary) lines.push(`    - chose: ${summary}`)
    } else if (d.selected_option_id) {
      lines.push(`    - selected option: \`${d.selected_option_id}\``)
    }
    if (d.belief_dependencies && d.belief_dependencies.length > 0) {
      const ids = d.belief_dependencies
        .slice(0, 4)
        .map((b) => `\`${b.slice(0, 8)}\``)
        .join(", ")
      const more =
        d.belief_dependencies.length > 4 ? `, …${d.belief_dependencies.length - 4} more` : ""
      lines.push(`    - belief dependencies: ${ids}${more}`)
    }
    if (d.made_by) {
      const when = d.made_at ? ` at ${d.made_at}` : ""
      lines.push(`    - made by \`${d.made_by}\`${when}`)
    }
  }
  return lines
}

function describeChosenOption(option: unknown): string | undefined {
  if (option === null || option === undefined) return undefined
  if (typeof option === "string") return option
  if (typeof option !== "object") return String(option)
  const o = option as Record<string, unknown>
  const label = typeof o.label === "string" ? o.label : undefined
  const rationale = typeof o.rationale === "string" ? o.rationale : undefined
  if (label && rationale) return `**${label}** — ${rationale}`
  if (label) return `**${label}**`
  if (rationale) return rationale
  return undefined
}

function renderActions(actions: ProjectedAction[]): string[] {
  if (actions.length === 0) return []
  const lines: string[] = []
  for (const { action, outcome, terminal_phase } of actions) {
    if (!action) {
      if (outcome) {
        lines.push(
          `- (outcome only, action not in this slice) action=\`${outcome.action_id.slice(0, 8)}\`: ${describeOutcome(outcome)}`,
        )
      }
      continue
    }
    lines.push(
      `- \`${action.tool}\` — ${action.intent}  ` +
        `(L${action.contract.required_level}, ${action.contract.blast_radius}, ` +
        `${action.contract.reversibility}, final phase \`${terminal_phase}\`)`,
    )
    if (action.approval) {
      const decision = action.approval.approved ? "approved" : "rejected"
      const reason = action.approval.reason ?? "(no reason given)"
      lines.push(`    - **${decision}** by \`${action.approval.approver_id}\`: ${reason}`)
    }
    if (outcome) {
      lines.push(`    - outcome: ${describeOutcome(outcome)}`)
    }
    const failureNote = lastAuditFailure(action)
    if (failureNote) {
      lines.push(`    - failure: ${failureNote}`)
    }
  }
  return lines
}

function renderTransitions(transitions: FirewallTransition[]): string[] {
  if (transitions.length === 0) return []
  const counts = new Map<string, number>()
  for (const t of transitions) {
    counts.set(t.kind, (counts.get(t.kind) ?? 0) + 1)
  }
  const lines: string[] = []
  const summary = Array.from(counts.entries())
    .map(([k, n]) => `${n} × \`${k}\``)
    .join(", ")
  lines.push(`Summary: ${summary}.`)
  lines.push("")
  for (const t of transitions) {
    if (t.kind === "claim.accepted") {
      lines.push(
        `- \`claim.accepted\` claim=\`${t.claim_id?.slice(0, 8) ?? "?"}\` ` +
          `by \`${t.by_actor_id ?? "?"}\``,
      )
    } else if (t.kind === "belief.adopted") {
      lines.push(
        `- \`belief.adopted\` belief=\`${t.belief_id?.slice(0, 8) ?? "?"}\` ` +
          `claim=\`${t.claim_id?.slice(0, 8) ?? "?"}\` ` +
          `authority=\`${t.by_authority ?? "?"}\``,
      )
    } else if (t.kind === "belief.transitioned") {
      lines.push(
        `- \`belief.transitioned\` belief=\`${t.belief_id?.slice(0, 8) ?? "?"}\` ` +
          `${t.axis ?? "?"}: \`${t.from_value ?? "?"}\` → \`${t.to_value ?? "?"}\` ` +
          `authority=\`${t.by_authority ?? "?"}\``,
      )
    } else {
      lines.push("- `firewall.unknown`")
    }
  }
  return lines
}

function renderCognitiveSummaries(summaries: ChainProjection["cognitive_summaries"]): string[] {
  if (summaries.length === 0) return []
  const lines: string[] = []
  for (const s of summaries) {
    const claimCount = s.claim_count ?? 0
    const beliefCount = s.belief_count ?? 0
    const keys = s.world_model_keys ?? []
    lines.push(
      `- observation \`${(s.observation_id ?? "?").slice(0, 8)}\`: ${claimCount} claim(s), ${beliefCount} belief(s)${keys.length > 0 ? `, world-model keys [${keys.join(", ")}]` : ""}`,
    )
  }
  return lines
}

function describeOutcome(outcome: Outcome): string {
  const effects =
    outcome.effect_observation_ids.length > 0
      ? `, ${outcome.effect_observation_ids.length} effect observation(s)`
      : ""
  const sideEffects =
    outcome.side_effects_observed.length > 0
      ? `, side effects: ${outcome.side_effects_observed.join(", ")}`
      : ""
  return `\`${outcome.result}\` in ${outcome.duration_ms}ms${effects}${sideEffects}`
}

function lastAuditFailure(action: Action): string | undefined {
  for (let i = action.audit.length - 1; i >= 0; i--) {
    const step = action.audit[i]
    if (step && (step.phase === "failed" || step.phase === "rejected")) {
      return step.detail ?? `phase \`${step.phase}\``
    }
  }
  return undefined
}
